apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: test-flows
  namespace: int
spec:
  pod:
    containers:
      runtime:
        image: >-
          407690149.dkr.ecr.us-east-1.amazonaws.com/openshift-cicd:test-flows-d31228ed88b7a5880d20f629d161