apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: test-flows
  namespace: int
spec:
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 100m
            memory: 300Mi