apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: test-flows
  namespace: int
spec:
  adminServerSecure: true
  createDashboardUsers: true
  designerFlowsOperationMode: disabled
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-C79J9U
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
        image: >-        
          407690150649.dkr.ecr.us-east-1.amazonaws.com/openshift-cicd:replacewithbakedimage
        imagePullPolicy: Always
    imagePullSecrets:
      - name: ecr-entitlement-key
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  version: 12.0.3.0-r1
  barURL: ''  